package io.github.chiselteam.chisel.content.compat;

import io.github.chiselteam.chisel.Chisel;
import io.github.chiselteam.chisel.api.model.ChiselModelHandlers;
import io.github.chiselteam.chisel.content.ChiselFamily;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockBehaviour;

import java.util.List;

public class AllTheModsFamilies {
    public static final ChiselFamily ATM_ANCIENT_STONE = ChiselFamily.build("atm_ancient_stone", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE))
                .addVariant("ancient_stone_array", ChiselModelHandlers.MULTIBLOCK_2X2).translation("ancient_stone_array", "Ancient Stone", "Array")
                .addVariant("ancient_stone_border_square", ChiselModelHandlers.CONNECTED).translation("ancient_stone_border_square", "Ancient Stone", "Square Border")
                .texture("ancient_stone_border_square", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_raw"))
                .addVariant("ancient_stone_braid").translation("ancient_stone_braid", "Ancient Stone", "Braid")
                .addVariant("ancient_stone_braid_encased", ChiselModelHandlers.CONNECTED).translation("ancient_stone_braid_encased", "Ancient Stone", "Encased Braid")
                .texture("ancient_stone_braid_encased", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_braid"))
                .addVariant("ancient_stone_bricks_cracked").translation("ancient_stone_bricks_cracked", "Ancient Stone", "Cracked Bricks")
                .addVariant("ancient_stone_bricks_encased", ChiselModelHandlers.CONNECTED).translation("ancient_stone_bricks_encased", "Ancient Stone", "Encased Bricks")
                .texture("ancient_stone_bricks_encased", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_bricks_solid"))
                .addVariant("ancient_stone_bricks_indent").translation("ancient_stone_bricks_indent", "Ancient Stone", "Indent Bricks")
                .addVariant("ancient_stone_bricks_inlayed").translation("ancient_stone_bricks_inlayed", "Ancient Stone", "Inlayed Bricks")
                .addVariant("ancient_stone_bricks_large", ChiselModelHandlers.MULTIBLOCK_2X2).translation("ancient_stone_bricks_large", "Ancient Stone", "Large Bricks")
                .texture("ancient_stone_bricks_large", "2x2_top_left", Chisel.prefix("block/atm_ancient_stone/ancient_stone_bricks_large"))
                .addVariant("ancient_stone_bricks_small").translation("ancient_stone_bricks_small", "Ancient Stone", "Small Bricks")
                .addVariant("ancient_stone_bricks_soft").translation("ancient_stone_bricks_soft", "Ancient Stone", "Soft Bricks")
                .addVariant("ancient_stone_bricks_solid").translation("ancient_stone_bricks_solid", "Ancient Stone", "Solid Bricks")
                .addVariant("ancient_stone_bricks_triple").translation("ancient_stone_bricks_triple", "Ancient Stone", "Triple Bricks")
                .addVariant("ancient_stone_bricks_vertical").translation("ancient_stone_bricks_vertical", "Ancient Stone", "Vertical Bricks")
                .addVariant("ancient_stone_chaotic", ChiselModelHandlers.MULTIBLOCK_3X3).translation("ancient_stone_chaotic", "Ancient Stone", "Chaotic")
                .addVariant("ancient_stone_chaotic_medium").translation("ancient_stone_chaotic_medium", "Ancient Stone", "Chaotic Medium")
                .addVariant("ancient_stone_chaotic_small").translation("ancient_stone_chaotic_small", "Ancient Stone", "Chaotic Small")
                .addVariant("ancient_stone_checker").translation("ancient_stone_checker", "Ancient Stone", "Checker")
                .addVariant("ancient_stone_checker_small").translation("ancient_stone_checker_small", "Ancient Stone", "Small Checker")
                .addVariant("ancient_stone_circular", ChiselModelHandlers.CONNECTED).translation("ancient_stone_circular", "Ancient Stone", "Circular")
                .texture("ancient_stone_circular", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_raw"))
                .addVariant("ancient_stone_cobble").translation("ancient_stone_cobble", "Ancient Stone", "Cobble")
                .addVariant("ancient_stone_cuts", ChiselModelHandlers.MULTIBLOCK_4X4).translation("ancient_stone_cuts", "Ancient Stone", "Cuts")
                .addVariant("ancient_stone_dent", ChiselModelHandlers.CONNECTED).translation("ancient_stone_dent", "Ancient Stone", "Dent")
                .texture("ancient_stone_dent", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_raw"))
                .addVariant("ancient_stone_french_1").translation("ancient_stone_french_1", "Ancient Stone", "French 1")
                .addVariant("ancient_stone_french_2").translation("ancient_stone_french_2", "Ancient Stone", "French 2")
                .addVariant("ancient_stone_indent", ChiselModelHandlers.CONNECTED).translation("ancient_stone_indent", "Ancient Stone", "Indent")
                .texture("ancient_stone_indent", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_raw"))
                .addVariant("ancient_stone_jellybean", ChiselModelHandlers.MULTIBLOCK_2X2).translation("ancient_stone_jellybean", "Ancient Stone", "Jellybean")
                .texture("ancient_stone_jellybean", "2x2_top_left", Chisel.prefix("block/atm_ancient_stone/ancient_stone_jellybean"))
                .addVariant("ancient_stone_layers").translation("ancient_stone_layers", "Ancient Stone", "Layers")
                .addVariant("ancient_stone_layers_connected", ChiselModelHandlers.CONNECTED).translation("ancient_stone_layers_connected", "Ancient Stone", "Layers Connected")
                .texture("ancient_stone_layers_connected", Chisel.prefix("block/atm_ancient_stone/ancient_stone_layers"))
                .texture("ancient_stone_layers_connected", "ctm_corner", Chisel.prefix("block/atm_ancient_stone/ancient_stone_layers_connected-ctm_corner"))
                .texture("ancient_stone_layers_connected", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_layers_connected-ctm_cornerless"))
                .texture("ancient_stone_layers_connected", "ctm_horizontal", Chisel.prefix("block/atm_ancient_stone/ancient_stone_layers_connected-ctm_horizontal"))
                .texture("ancient_stone_layers_connected", "ctm_vertical", Chisel.prefix("block/atm_ancient_stone/ancient_stone_layers_connected-ctm_vertical"))
                .addVariant("ancient_stone_line_horizontal").translation("ancient_stone_line_horizontal", "Ancient Stone", "Horizontal Line")
                .addVariant("ancient_stone_line_vertical").translation("ancient_stone_line_vertical", "Ancient Stone", "Vertical Line")
                .addVariant("ancient_stone_meander_horizontal", ChiselModelHandlers.CTMH).translation("ancient_stone_meander_horizontal", "Ancient Stone", "Horizontal Meander")
                .texture("ancient_stone_meander_horizontal", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_meander_horizontal-top"))
                .addVariant("ancient_stone_meander_vertical", ChiselModelHandlers.CTMV).translation("ancient_stone_meander_vertical", "Ancient Stone", "Vertical Meander")
                .texture("ancient_stone_meander_vertical", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_meander_vertical-top"))
                .texture("ancient_stone_meander_vertical", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_meander_vertical-side"))
                .addVariant("ancient_stone_mosaic", ChiselModelHandlers.CONNECTED).translation("ancient_stone_mosaic", "Ancient Stone", "Mosaic")
                .texture("ancient_stone_mosaic", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_raw"))
                .addVariant("ancient_stone_ornate_small").translation("ancient_stone_ornate_small", "Ancient Stone", "Small Ornate")
                .addVariant("ancient_stone_panel").translation("ancient_stone_panel", "Ancient Stone", "Panel")
                .addVariant("ancient_stone_pillar", ChiselModelHandlers.TBS).translation("ancient_stone_pillar", "Ancient Stone", "Pillar")
                .texture("ancient_stone_pillar", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar-top"))
                .addVariant("ancient_stone_pillar_basic", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_basic", "Ancient Stone", "Basic Pillar")
                .texture("ancient_stone_pillar_basic", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_basic", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-side"))
                .addVariant("ancient_stone_pillar_basic_dent", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_basic_dent", "Ancient Stone", "Basic Dent Pillar")
                .texture("ancient_stone_pillar_basic_dent", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_basic_dent", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_basic_dent", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_dent-side"))
                .addVariant("ancient_stone_pillar_basic_plain", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_basic_plain", "Ancient Stone", "Basic Plain Pillar")
                .texture("ancient_stone_pillar_basic_plain", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_basic_plain", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_basic_plain", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_plain-side"))
                .addVariant("ancient_stone_pillar_basic_round", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_basic_round", "Ancient Stone", "Basic Round Pillar")
                .texture("ancient_stone_pillar_basic_round", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_basic_round", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_basic_round", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_round-side"))
                .addVariant("ancient_stone_pillar_basic_spiral", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_basic_spiral", "Ancient Stone", "Basic Spiral Pillar")
                .texture("ancient_stone_pillar_basic_spiral", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_basic_spiral", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_basic_spiral", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_spiral-side"))
                .addVariant("ancient_stone_pillar_classic", ChiselModelHandlers.TBS).translation("ancient_stone_pillar_classic", "Ancient Stone", "Classic Pillar")
                .texture("ancient_stone_pillar_classic", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_classic-top"))
                .addVariant("ancient_stone_pillar_classic_large", ChiselModelHandlers.TBS).translation("ancient_stone_pillar_classic_large", "Ancient Stone", "Large Classic Pillar")
                .texture("ancient_stone_pillar_classic_large", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_classic_large-top"))
                .addVariant("ancient_stone_pillar_ionic", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_ionic", "Ancient Stone", "Ionic Pillar")
                .texture("ancient_stone_pillar_ionic", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_ionic", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_ionic", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_ionic-side"))
                .addVariant("ancient_stone_pillar_ionic_dent", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_ionic_dent", "Ancient Stone", "Ionic Dent Pillar")
                .texture("ancient_stone_pillar_ionic_dent", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_ionic_dent", "side", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_ionic-side"))
                .texture("ancient_stone_pillar_ionic_dent", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_ionic_dent", "vertical_both", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_dent-vertical_both"))
                .texture("ancient_stone_pillar_ionic_dent", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_ionic-side"))
                .addVariant("ancient_stone_pillar_ionic_plain", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_ionic_plain", "Ancient Stone", "Ionic Plain Pillar")
                .texture("ancient_stone_pillar_ionic_plain", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_ionic_plain", "side", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_ionic-side"))
                .texture("ancient_stone_pillar_ionic_plain", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_ionic_plain", "vertical_both", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_plain-vertical_both"))
                .texture("ancient_stone_pillar_ionic_plain", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_ionic-side"))
                .addVariant("ancient_stone_pillar_ionic_round", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_ionic_round", "Ancient Stone", "Ionic Round Pillar")
                .texture("ancient_stone_pillar_ionic_round", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_ionic_round", "side", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_ionic-side"))
                .texture("ancient_stone_pillar_ionic_round", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_ionic_round", "vertical_both", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_round-vertical_both"))
                .texture("ancient_stone_pillar_ionic_round", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_ionic-side"))
                .addVariant("ancient_stone_pillar_ionic_spiral", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_ionic_spiral", "Ancient Stone", "Ionic Spiral Pillar")
                .texture("ancient_stone_pillar_ionic_spiral", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_ionic_spiral", "side", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_ionic-side"))
                .texture("ancient_stone_pillar_ionic_spiral", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_ionic_spiral", "vertical_both", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_spiral-vertical_both"))
                .texture("ancient_stone_pillar_ionic_spiral", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_ionic-side"))
                .addVariant("ancient_stone_pillar_large_basic_triple", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_large_basic_triple", "Ancient Stone", "Large Basic Triple Pillar")
                .texture("ancient_stone_pillar_large_basic_triple", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_large_basic_triple", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_large_basic_triple", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_large_basic_triple-side"))
                .addVariant("ancient_stone_pillar_large_ionic_triple", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_large_ionic_triple", "Ancient Stone", "Large Ionic Triple Pillar")
                .texture("ancient_stone_pillar_large_ionic_triple", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_large_ionic_triple", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_large_ionic_triple", "vertical_both", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_large_basic_triple-vertical_both"))
                .texture("ancient_stone_pillar_large_ionic_triple", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_large_ionic_triple-side"))
                .addVariant("ancient_stone_pillar_meander", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_meander", "Ancient Stone", "Meander Pillar")
                .texture("ancient_stone_pillar_meander", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_meander", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_meander", "vertical_both", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_ionic-vertical_both"))
                .texture("ancient_stone_pillar_meander", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_meander-side"))
                .addVariant("ancient_stone_pillar_meander_dent", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_meander_dent", "Ancient Stone", "Meander Dent Pillar")
                .texture("ancient_stone_pillar_meander_dent", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_meander_dent", "side", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_meander-side"))
                .texture("ancient_stone_pillar_meander_dent", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_meander_dent", "vertical_both", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_dent-vertical_both"))
                .texture("ancient_stone_pillar_meander_dent", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_meander-side"))
                .addVariant("ancient_stone_pillar_meander_plain", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_meander_plain", "Ancient Stone", "Meander Plain Pillar")
                .texture("ancient_stone_pillar_meander_plain", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_meander_plain", "side", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_meander-side"))
                .texture("ancient_stone_pillar_meander_plain", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_meander_plain", "vertical_both", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_plain-vertical_both"))
                .texture("ancient_stone_pillar_meander_plain", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_meander-side"))
                .addVariant("ancient_stone_pillar_meander_round", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_meander_round", "Ancient Stone", "Meander Round Pillar")
                .texture("ancient_stone_pillar_meander_round", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_meander_round", "side", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_meander-side"))
                .texture("ancient_stone_pillar_meander_round", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_meander_round", "vertical_both", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_round-vertical_both"))
                .texture("ancient_stone_pillar_meander_round", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_meander-side"))
                .addVariant("ancient_stone_pillar_meander_spiral", ChiselModelHandlers.CTMV).translation("ancient_stone_pillar_meander_spiral", "Ancient Stone", "Meander Spiral Pillar")
                .texture("ancient_stone_pillar_meander_spiral", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_meander_spiral", "side", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_meander-side"))
                .texture("ancient_stone_pillar_meander_spiral", "top", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic-top"))
                .texture("ancient_stone_pillar_meander_spiral", "vertical_both", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_basic_spiral-vertical_both"))
                .texture("ancient_stone_pillar_meander_spiral", "vertical_none", Chisel.prefix("block/atm_ancient_stone/ancient_stone_pillar_meander-side"))
                .addVariant("ancient_stone_plate").translation("ancient_stone_plate", "Ancient Stone", "Plate")
                .addVariant("ancient_stone_plate_connected", ChiselModelHandlers.CONNECTED).translation("ancient_stone_plate_connected", "Ancient Stone", "Plate Connected")
                .texture("ancient_stone_plate_connected", Chisel.prefix("block/atm_ancient_stone/ancient_stone_plate"))
                .texture("ancient_stone_plate_connected", "ctm_corner", Chisel.prefix("block/atm_ancient_stone/ancient_stone_plate_connected-ctm_corner"))
                .texture("ancient_stone_plate_connected", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_raw"))
                .texture("ancient_stone_plate_connected", "ctm_horizontal", Chisel.prefix("block/atm_ancient_stone/ancient_stone_plate_connected-ctm_horizontal"))
                .texture("ancient_stone_plate_connected", "ctm_vertical", Chisel.prefix("block/atm_ancient_stone/ancient_stone_plate_connected-ctm_vertical"))
                .addVariant("ancient_stone_polished").translation("ancient_stone_polished", "Ancient Stone", "Polished")
                .addVariant("ancient_stone_polished_encased", ChiselModelHandlers.CONNECTED).translation("ancient_stone_polished_encased", "Ancient Stone", "Polished Encased")
                .addVariant("ancient_stone_prism").translation("ancient_stone_prism", "Ancient Stone", "Prismatic")
                .addVariant("ancient_stone_raw").translation("ancient_stone_raw", "Ancient Stone", "Raw")
                .addVariant("ancient_stone_road").translation("ancient_stone_road", "Ancient Stone", "Road")
                .addVariant("ancient_stone_slanted", ChiselModelHandlers.MULTIBLOCK_2X2).translation("ancient_stone_slanted", "Ancient Stone", "Slanted")
                .addVariant("ancient_stone_tiles").translation("ancient_stone_tiles", "Ancient Stone", "Tiles")
                .addVariant("ancient_stone_tiles_large", ChiselModelHandlers.CONNECTED).translation("ancient_stone_tiles_large", "Ancient Stone", "Large Tiles")
                .texture("ancient_stone_tiles_large", Chisel.prefix("block/atm_ancient_stone/ancient_stone_polished"))
                .texture("ancient_stone_tiles_large", "ctm_corner", Chisel.prefix("block/atm_ancient_stone/ancient_stone_tiles_large-ctm_corner"))
                .texture("ancient_stone_tiles_large", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_raw"))
                .texture("ancient_stone_tiles_large", "ctm_horizontal", Chisel.prefix("block/atm_ancient_stone/ancient_stone_tiles_large-ctm_horizontal"))
                .texture("ancient_stone_tiles_large", "ctm_vertical", Chisel.prefix("block/atm_ancient_stone/ancient_stone_tiles_large-ctm_vertical"))
                .addVariant("ancient_stone_tiles_small").translation("ancient_stone_tiles_small", "Ancient Stone", "Small Tiles")
                .addVariant("ancient_stone_twisted", ChiselModelHandlers.TBS).translation("ancient_stone_twisted", "Ancient Stone", "Twisted")
                .texture("ancient_stone_twisted", "bottom", Chisel.prefix("block/atm_ancient_stone/ancient_stone_twisted-top"))
                .addVariant("ancient_stone_weaver", ChiselModelHandlers.CONNECTED).translation("ancient_stone_weaver", "Ancient Stone", "Weaver")
                .addVariant("ancient_stone_zag", ChiselModelHandlers.MULTIBLOCK_2X2).translation("ancient_stone_zag", "Ancient Stone", "Zag")
                .texture("ancient_stone_zag", "2x2_top_left", Chisel.prefix("block/atm_ancient_stone/ancient_stone_zag"))
                .addVariant("ancient_stone_crate", ChiselModelHandlers.CONNECTED).translation("ancient_stone_crate", "Ancient Stone", "Crate")
                .addVariant("ancient_stone_herringbone").translation("ancient_stone_herringbone", "Ancient Stone", "Herringbone")
                .addVariant("ancient_stone_herringbone_encased", ChiselModelHandlers.CONNECTED).translation("ancient_stone_herringbone_encased", "Ancient Stone", "Encased Herringbone")
                .texture("ancient_stone_herringbone_encased", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_herringbone"))
                .addVariant("ancient_stone_medallion").translation("ancient_stone_medallion", "Ancient Stone", "Medallion")
                .addVariant("ancient_stone_medallion_encased", ChiselModelHandlers.CONNECTED).translation("ancient_stone_medallion_encased", "Ancient Stone", "Encased Medallion")
                .texture("ancient_stone_medallion_encased", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_medallion"))
                .addVariant("ancient_stone_dots").translation("ancient_stone_dots", "Ancient Stone", "Dots")
                .addVariant("ancient_stone_dots_encased", ChiselModelHandlers.CONNECTED).translation("ancient_stone_dots_encased", "Ancient Stone", "Encased Dots")
                .texture("ancient_stone_dots_encased", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_dots"))
                .addVariant("ancient_stone_heart").translation("ancient_stone_heart", "Ancient Stone", "Heart")
                .addVariant("ancient_stone_star").translation("ancient_stone_star", "Ancient Stone", "Star")
                .addVariant("ancient_stone_plating").translation("ancient_stone_plating", "Ancient Stone", "Plating")
                .addVariant("ancient_stone_lodestone").translation("ancient_stone_lodestone", "Ancient Stone", "Lodestone")
                .addVariant("ancient_stone_lodestone_connected", ChiselModelHandlers.CONNECTED).translation("ancient_stone_lodestone_connected", "Ancient Stone", "Lodestone Connected")
                .texture("ancient_stone_lodestone_connected", Chisel.prefix("block/atm_ancient_stone/ancient_stone_lodestone"))
                .texture("ancient_stone_lodestone_connected", "ctm_corner", Chisel.prefix("block/atm_ancient_stone/ancient_stone_lodestone_connected-ctm_corner"))
                .texture("ancient_stone_lodestone_connected", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_lodestone"))
                .texture("ancient_stone_lodestone_connected", "ctm_horizontal", Chisel.prefix("block/atm_ancient_stone/ancient_stone_lodestone_connected-ctm_horizontal"))
                .texture("ancient_stone_lodestone_connected", "ctm_vertical", Chisel.prefix("block/atm_ancient_stone/ancient_stone_lodestone_connected-ctm_vertical"))
                .addVariant("ancient_stone_plank").translation("ancient_stone_plank", "Ancient Stone", "Plank")
                .addVariant("ancient_stone_plank_connected", ChiselModelHandlers.CONNECTED).translation("ancient_stone_plank_connected", "Ancient Stone", "Plank Connected")
                .texture("ancient_stone_plank_connected", Chisel.prefix("block/atm_ancient_stone/ancient_stone_plank"))
                .texture("ancient_stone_plank_connected", "ctm_corner", Chisel.prefix("block/atm_ancient_stone/ancient_stone_plank_connected-ctm_corner"))
                .texture("ancient_stone_plank_connected", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_plank_connected-ctm_cornerless"))
                .texture("ancient_stone_plank_connected", "ctm_horizontal", Chisel.prefix("block/atm_ancient_stone/ancient_stone_plank_connected-ctm_horizontal"))
                .texture("ancient_stone_plank_connected", "ctm_vertical", Chisel.prefix("block/atm_ancient_stone/ancient_stone_plank_connected-ctm_vertical"))
                .addVariant("ancient_stone_frame").translation("ancient_stone_frame", "Ancient Stone", "Frame")
                .addVariant("ancient_stone_panel_1").translation("ancient_stone_panel_1", "Ancient Stone", "Panel 1")
                .addVariant("ancient_stone_panel_2").translation("ancient_stone_panel_2", "Ancient Stone", "Panel 2")
                .addVariant("ancient_stone_panel_3").translation("ancient_stone_panel_3", "Ancient Stone", "Panel 3")
                .addVariant("ancient_stone_skull_creeper").translation("ancient_stone_skull_creeper", "Ancient Stone", "Creeper Skull")
                .addVariant("ancient_stone_skull_skeleton").translation("ancient_stone_skull_skeleton", "Ancient Stone", "Skeleton Skull")
                .addVariant("ancient_stone_stripes").translation("ancient_stone_stripes", "Ancient Stone", "Stripes")
                .addVariant("ancient_stone_stripes_encased", ChiselModelHandlers.CONNECTED).translation("ancient_stone_stripes_encased", "Ancient Stone", "Encased Stripes")
                .texture("ancient_stone_stripes_encased", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_stripes"))
                .addVariant("ancient_stone_chisel_1").translation("ancient_stone_chisel_1", "Ancient Stone", "Chisel 1")
                .addVariant("ancient_stone_chisel_2").translation("ancient_stone_chisel_2", "Ancient Stone", "Chisel 2")
                .addVariant("ancient_stone_chisel_3").translation("ancient_stone_chisel_3", "Ancient Stone", "Chisel 3")
                .addVariant("ancient_stone_chisel_4").translation("ancient_stone_chisel_4", "Ancient Stone", "Chisel 4")
                .addVariant("ancient_stone_chisel_5").translation("ancient_stone_chisel_5", "Ancient Stone", "Chisel 5")
                .addVariant("ancient_stone_chisel_6").translation("ancient_stone_chisel_6", "Ancient Stone", "Chisel 6")
                .addVariant("ancient_stone_facet").translation("ancient_stone_facet", "Ancient Stone", "Facet")
                .addVariant("ancient_stone_facet_small").translation("ancient_stone_facet_small", "Ancient Stone", "Small Facet")
                .addVariant("ancient_stone_facet_small_encased", ChiselModelHandlers.CONNECTED).translation("ancient_stone_facet_small_encased", "Ancient Stone", "Encased Small Facet")
                .texture("ancient_stone_facet_small_encased", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_facet_small"))
                .addVariant("ancient_stone_shiny").translation("ancient_stone_shiny", "Ancient Stone", "Shiny")
                .addVariant("ancient_stone_shiny_connected", ChiselModelHandlers.CONNECTED).translation("ancient_stone_shiny_connected", "Ancient Stone", "Shiny Connected")
                .texture("ancient_stone_shiny_connected", Chisel.prefix("block/atm_ancient_stone/ancient_stone_shiny"))
                .texture("ancient_stone_shiny_connected", "ctm_corner", Chisel.prefix("block/atm_ancient_stone/ancient_stone_shiny_connected-ctm_corner"))
                .texture("ancient_stone_shiny_connected", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_shiny_connected-ctm_cornerless"))
                .texture("ancient_stone_shiny_connected", "ctm_horizontal", Chisel.prefix("block/atm_ancient_stone/ancient_stone_shiny_connected-ctm_horizontal"))
                .texture("ancient_stone_shiny_connected", "ctm_vertical", Chisel.prefix("block/atm_ancient_stone/ancient_stone_shiny_connected-ctm_vertical"))
                .addVariant("ancient_stone_gem").translation("ancient_stone_gem", "Ancient Stone", "Gem")
                .addVariant("ancient_stone_gem_1").translation("ancient_stone_gem_1", "Ancient Stone", "Gem 1")
                .addVariant("ancient_stone_gem_1_connected", ChiselModelHandlers.CONNECTED).translation("ancient_stone_gem_1_connected", "Ancient Stone", "Gem 1 Connected")
                .texture("ancient_stone_gem_1_connected", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_1"))
                .texture("ancient_stone_gem_1_connected", "ctm_corner", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_1_connected-ctm_corner"))
                .texture("ancient_stone_gem_1_connected", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_raw"))
                .texture("ancient_stone_gem_1_connected", "ctm_horizontal", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_1_connected-ctm_horizontal"))
                .texture("ancient_stone_gem_1_connected", "ctm_vertical", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_1_connected-ctm_vertical"))
                .addVariant("ancient_stone_gem_2").translation("ancient_stone_gem_2", "Ancient Stone", "Gem 2")
                .addVariant("ancient_stone_gem_2_connected", ChiselModelHandlers.CONNECTED).translation("ancient_stone_gem_2_connected", "Ancient Stone", "Gem 2 Connected")
                .texture("ancient_stone_gem_2_connected", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_2"))
                .texture("ancient_stone_gem_2_connected", "ctm_corner", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_2_connected-ctm_corner"))
                .texture("ancient_stone_gem_2_connected", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_raw"))
                .texture("ancient_stone_gem_2_connected", "ctm_horizontal", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_2_connected-ctm_horizontal"))
                .texture("ancient_stone_gem_2_connected", "ctm_vertical", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_2_connected-ctm_vertical"))
                .addVariant("ancient_stone_gem_3").translation("ancient_stone_gem_3", "Ancient Stone", "Gem 3")
                .addVariant("ancient_stone_gem_3_connected", ChiselModelHandlers.CONNECTED).translation("ancient_stone_gem_3_connected", "Ancient Stone", "Gem 3 Connected")
                .texture("ancient_stone_gem_3_connected", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_3"))
                .texture("ancient_stone_gem_3_connected", "ctm_corner", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_3_connected-ctm_corner"))
                .texture("ancient_stone_gem_3_connected", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_3_connected-ctm_cornerless"))
                .texture("ancient_stone_gem_3_connected", "ctm_horizontal", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_3_connected-ctm_horizontal"))
                .texture("ancient_stone_gem_3_connected", "ctm_vertical", Chisel.prefix("block/atm_ancient_stone/ancient_stone_gem_3_connected-ctm_vertical"))
                .addVariant("ancient_stone_bricks_square").translation("ancient_stone_bricks_square", "Ancient Stone", "Square Bricks")
                .addVariant("ancient_stone_slab").translation("ancient_stone_slab", "Ancient Stone", "Slab")
                .addVariant("ancient_stone_scaffold").translation("ancient_stone_scaffold", "Ancient Stone", "Scaffold")
                .addVariant("ancient_stone_scaffold_encased", ChiselModelHandlers.CONNECTED).translation("ancient_stone_scaffold_encased", "Ancient Stone", "Encased Scaffold")
                .texture("ancient_stone_scaffold_encased", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_scaffold"))
                .addVariant("ancient_stone_tiles_inlayed").translation("ancient_stone_tiles_inlayed", "Ancient Stone", "Inlayed Tiles")
                .addVariant("ancient_stone_waves", ChiselModelHandlers.MULTIBLOCK_2X2).translation("ancient_stone_waves", "Ancient Stone", "Waves")
                .texture("ancient_stone_waves", "2x2_top_left", Chisel.prefix("block/atm_ancient_stone/ancient_stone_waves"))
                .addVariant("ancient_stone_parquet").translation("ancient_stone_parquet", "Ancient Stone", "Parquet")
                .addVariant("ancient_stone_parquet_encased", ChiselModelHandlers.CONNECTED).translation("ancient_stone_parquet_encased", "Ancient Stone", "Encased Parquet")
                .texture("ancient_stone_parquet_encased", "ctm_cornerless", Chisel.prefix("block/atm_ancient_stone/ancient_stone_parquet"))
                .build());
        
        /* public static final ChiselFamily ATM_ALLTHEMODIUM = ChiselFamily.build("atm_allthemodium", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .build());

        public static final ChiselFamily ATM_UNOBTAINIUM_ALLTHEMODIUM = ChiselFamily.build("atm_unobtainium_allthemodium", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .build());

        public static final ChiselFamily ATM_UNOBTAINIUM = ChiselFamily.build("atm_unobtainium", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .build());

        public static final ChiselFamily ATM_UNOBTAINIUM_VIBRANIUM = ChiselFamily.build("atm_unobtainium_vibranium", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .build());

        public static final ChiselFamily ATM_VIBRANIUM_ALLTHEMODIUM = ChiselFamily.build("atm_vibranium_allthemodium", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .build());

        public static final ChiselFamily ATM_VIBRANIUM = ChiselFamily.build("atm_vibranium", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .build());

        */
  private static final List<ChiselFamily> FAMILIES = List.of(ATM_ANCIENT_STONE);

    private AllTheModsFamilies() {
    }

    public static List<ChiselFamily> families() {
        return FAMILIES;
    }
}
