package io.github.chiselteam.chisel.content.compat;

import io.github.chiselteam.chisel.Chisel;
import io.github.chiselteam.chisel.api.model.ChiselModelHandlers;
import io.github.chiselteam.chisel.content.ChiselFamily;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockBehaviour;

import java.util.List;

public class ModdedMetalFamilies {
    public static final ChiselFamily CHARCOAL, COAL_COKE, ALUMINUM, BRONZE, COBALT, ELECTRUM, INVAR, LEAD, NICKEL, PLATINUM, SILVER, STEEL, THAUMIUM, TIN, URANIUM;
    private static final List<ChiselFamily> FAMILIES;

    static {
        CHARCOAL = ChiselFamily.build("charcoal", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE))
                .addVariant("charcoal_array", ChiselModelHandlers.MULTIBLOCK_2X2).translation("charcoal_array", "Charcoal", "Array")
                .texture("charcoal_array", "2x2_top_left", Chisel.prefix("block/charcoal/charcoal_array"))
                .addVariant("charcoal_border_square", ChiselModelHandlers.CONNECTED).translation("charcoal_border_square", "Charcoal", "Square Border")
                .texture("charcoal_border_square", "ctm_corner", Chisel.prefix("block/charcoal/charcoal_border_square"))
                .texture("charcoal_border_square", "ctm_horizontal", Chisel.prefix("block/charcoal/charcoal_border_square"))
                .texture("charcoal_border_square", "ctm_vertical", Chisel.prefix("block/charcoal/charcoal_border_square"))
                .addVariant("charcoal_braid").translation("charcoal_braid", "Charcoal", "Braid")
                .addVariant("charcoal_braid_encased", ChiselModelHandlers.CONNECTED).translation("charcoal_braid_encased", "Charcoal", "Encased Braid")
                .texture("charcoal_braid_encased", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_braid"))
                .addVariant("charcoal_cracked_bricks").translation("charcoal_cracked_bricks", "Charcoal", "Cracked Bricks")
                .addVariant("charcoal_encased_bricks", ChiselModelHandlers.CONNECTED).translation("charcoal_encased_bricks", "Charcoal", "Encased Bricks")
                .addVariant("charcoal_bricks_indent").translation("charcoal_bricks_indent", "Charcoal", "Indent Bricks")
                .addVariant("charcoal_bricks_inlayed").translation("charcoal_bricks_inlayed", "Charcoal", "Inlayed Bricks")
                .addVariant("charcoal_bricks_large", ChiselModelHandlers.MULTIBLOCK_2X2).translation("charcoal_bricks_large", "Charcoal", "Large Bricks")
                .texture("charcoal_bricks_large", "2x2_bottom_right", Chisel.prefix("block/charcoal/charcoal_bricks_large"))
                .texture("charcoal_bricks_large", "2x2_top_left", Chisel.prefix("block/charcoal/charcoal_bricks_large"))
                .texture("charcoal_bricks_large", "2x2_top_right", Chisel.prefix("block/charcoal/charcoal_bricks_large-2x2_bottom_left"))
                .addVariant("charcoal_small_bricks").translation("charcoal_small_bricks", "Charcoal", "Small Bricks")
                .addVariant("charcoal_soft_bricks").translation("charcoal_soft_bricks", "Charcoal", "Soft Bricks")
                .addVariant("charcoal_solid_bricks").translation("charcoal_solid_bricks", "Charcoal", "Solid Bricks")
                .addVariant("charcoal_triple_bricks").translation("charcoal_triple_bricks", "Charcoal", "Triple Bricks")
                .addVariant("charcoal_bricks_vertical").translation("charcoal_bricks_vertical", "Charcoal", "Vertical Bricks")
                .addVariant("charcoal_chaotic_bricks", ChiselModelHandlers.MULTIBLOCK_3X3).translation("charcoal_chaotic_bricks", "Charcoal", "Chaotic Bricks")
                .texture("charcoal_chaotic_bricks", "3x3_top_left", Chisel.prefix("block/charcoal/charcoal_chaotic_bricks"))
                .addVariant("charcoal_chaotic_medium").translation("charcoal_chaotic_medium", "Charcoal", "Charcoal Bricks")
                .addVariant("charcoal_chaotic_small").translation("charcoal_chaotic_small", "Charcoal", "Charcoal Small Tiles")
                .addVariant("charcoal_checker").translation("charcoal_checker", "Charcoal", "Checker")
                .addVariant("charcoal_checker_small").translation("charcoal_checker_small", "Charcoal", "Small Checker")
                .addVariant("charcoal_circular", ChiselModelHandlers.CONNECTED).translation("charcoal_circular", "Charcoal", "Circular")
                .addVariant("charcoal_cracked").translation("charcoal_cracked", "Charcoal", "Cracked")
                .addVariant("charcoal_cuts", ChiselModelHandlers.MULTIBLOCK_4X4).translation("charcoal_cuts", "Charcoal", "Cuts")
                .texture("charcoal_cuts", "4x4_row_0_column_0", Chisel.prefix("block/charcoal/charcoal_cuts"))
                .addVariant("charcoal_dent", ChiselModelHandlers.CONNECTED).translation("charcoal_dent", "Charcoal", "Dent")
                .addVariant("charcoal_french_1").translation("charcoal_french_1", "Charcoal", "French 1")
                .addVariant("charcoal_french_2").translation("charcoal_french_2", "Charcoal", "French 2")
                .addVariant("charcoal_indent", ChiselModelHandlers.CONNECTED).translation("charcoal_indent", "Charcoal", "Indent")
                .texture("charcoal_indent", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_border_square-ctm_cornerless"))
                .addVariant("charcoal_jellybean", ChiselModelHandlers.MULTIBLOCK_2X2).translation("charcoal_jellybean", "Charcoal", "Jellybean")
                .texture("charcoal_jellybean", "2x2_top_left", Chisel.prefix("block/charcoal/charcoal_jellybean"))
                .addVariant("charcoal_layers").translation("charcoal_layers", "Charcoal", "Layers")
                .texture("charcoal_layers", Chisel.prefix("block/charcoal/charcoal_layers_connected"))
                .addVariant("charcoal_layers_connected", ChiselModelHandlers.CONNECTED).translation("charcoal_layers_connected", "Charcoal", "Layers Connected")
                .texture("charcoal_layers_connected", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_layers_connected-ctm_corner"))
                .texture("charcoal_layers_connected", "ctm_horizontal", Chisel.prefix("block/charcoal/charcoal_layers_connected"))
                .texture("charcoal_layers_connected", "ctm_vertical", Chisel.prefix("block/charcoal/charcoal_layers_connected-ctm_corner"))
                .addVariant("charcoal_line_horizontal").translation("charcoal_line_horizontal", "Charcoal", "Horizontal Line")
                .addVariant("charcoal_line_vertical").translation("charcoal_line_vertical", "Charcoal", "Vertical Line")
                .addVariant("charcoal_meander_horizontal", ChiselModelHandlers.CTMH).translation("charcoal_meander_horizontal", "Charcoal", "Horizontal Meander")
                .texture("charcoal_meander_horizontal", "top", Chisel.prefix("block/charcoal/charcoal_meander_horizontal-bottom"))
                .addVariant("charcoal_meander_vertical", ChiselModelHandlers.CTMV).translation("charcoal_meander_vertical", "Charcoal", "Vertical Meander")
                .texture("charcoal_meander_vertical", "top", Chisel.prefix("block/charcoal/charcoal_meander_vertical-bottom"))
                .texture("charcoal_meander_vertical", "vertical_none", Chisel.prefix("block/charcoal/charcoal_meander_vertical-side"))
                .addVariant("charcoal_mosaic", ChiselModelHandlers.CONNECTED).translation("charcoal_mosaic", "Charcoal", "Mosaic")
                .addVariant("charcoal_ornate").translation("charcoal_ornate", "Charcoal", "Ornate Charcoal")
                .addVariant("charcoal_panel").translation("charcoal_panel", "Charcoal", "Panel")
                .addVariant("charcoal_pillar", ChiselModelHandlers.TBS).translation("charcoal_pillar", "Charcoal", "Pillar")
                .texture("charcoal_pillar", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar-top"))
                .addVariant("charcoal_pillar_basic", ChiselModelHandlers.CTMV).translation("charcoal_pillar_basic", "Charcoal", "Basic Pillar")
                .texture("charcoal_pillar_basic", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_basic", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_basic-side"))
                .addVariant("charcoal_pillar_basic_dent", ChiselModelHandlers.CTMV).translation("charcoal_pillar_basic_dent", "Charcoal", "Basic Dent Pillar")
                .texture("charcoal_pillar_basic_dent", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_basic_dent", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_basic_dent", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_basic_dent-side"))
                .addVariant("charcoal_pillar_basic_plain", ChiselModelHandlers.CTMV).translation("charcoal_pillar_basic_plain", "Charcoal", "Basic Plain Pillar")
                .texture("charcoal_pillar_basic_plain", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_basic_plain", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_basic_plain", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_basic_plain-side"))
                .addVariant("charcoal_pillar_basic_round", ChiselModelHandlers.CTMV).translation("charcoal_pillar_basic_round", "Charcoal", "Basic Round Pillar")
                .texture("charcoal_pillar_basic_round", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_basic_round", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_basic_round", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_basic_round-side"))
                .addVariant("charcoal_pillar_basic_spiral", ChiselModelHandlers.CTMV).translation("charcoal_pillar_basic_spiral", "Charcoal", "Basic Spiral Pillar")
                .texture("charcoal_pillar_basic_spiral", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_basic_spiral", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_basic_spiral", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_basic_spiral-side"))
                .addVariant("charcoal_pillar_classic", ChiselModelHandlers.TBS).translation("charcoal_pillar_classic", "Charcoal", "Classic Pillar")
                .texture("charcoal_pillar_classic", "top", Chisel.prefix("block/charcoal/charcoal_pillar_classic-bottom"))
                .addVariant("charcoal_pillar_classic_large", ChiselModelHandlers.TBS).translation("charcoal_pillar_classic_large", "Charcoal", "Large Classic Pillar")
                .texture("charcoal_pillar_classic_large", "top", Chisel.prefix("block/charcoal/charcoal_pillar_classic_large-bottom"))
                .addVariant("charcoal_pillar_ionic", ChiselModelHandlers.CTMV).translation("charcoal_pillar_ionic", "Charcoal", "Ionic Pillar")
                .texture("charcoal_pillar_ionic", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_ionic", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_ionic", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_ionic-side"))
                .addVariant("charcoal_pillar_ionic_dent", ChiselModelHandlers.CTMV).translation("charcoal_pillar_ionic_dent", "Charcoal", "Ionic Dent Pillar")
                .texture("charcoal_pillar_ionic_dent", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_ionic_dent", "side", Chisel.prefix("block/charcoal/charcoal_pillar_ionic-side"))
                .texture("charcoal_pillar_ionic_dent", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_ionic_dent", "vertical_both", Chisel.prefix("block/charcoal/charcoal_pillar_basic_dent-vertical_both"))
                .texture("charcoal_pillar_ionic_dent", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_ionic-side"))
                .addVariant("charcoal_pillar_ionic_plain", ChiselModelHandlers.CTMV).translation("charcoal_pillar_ionic_plain", "Charcoal", "Ionic Plain Pillar")
                .texture("charcoal_pillar_ionic_plain", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_ionic_plain", "side", Chisel.prefix("block/charcoal/charcoal_pillar_ionic-side"))
                .texture("charcoal_pillar_ionic_plain", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_ionic_plain", "vertical_both", Chisel.prefix("block/charcoal/charcoal_pillar_basic_plain-vertical_both"))
                .texture("charcoal_pillar_ionic_plain", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_ionic-side"))
                .addVariant("charcoal_pillar_ionic_round", ChiselModelHandlers.CTMV).translation("charcoal_pillar_ionic_round", "Charcoal", "Ionic Round Pillar")
                .texture("charcoal_pillar_ionic_round", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_ionic_round", "side", Chisel.prefix("block/charcoal/charcoal_pillar_ionic-side"))
                .texture("charcoal_pillar_ionic_round", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_ionic_round", "vertical_both", Chisel.prefix("block/charcoal/charcoal_pillar_basic_round-vertical_both"))
                .texture("charcoal_pillar_ionic_round", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_ionic-side"))
                .addVariant("charcoal_pillar_ionic_spiral", ChiselModelHandlers.CTMV).translation("charcoal_pillar_ionic_spiral", "Charcoal", "Ionic Spiral Pillar")
                .texture("charcoal_pillar_ionic_spiral", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_ionic_spiral", "side", Chisel.prefix("block/charcoal/charcoal_pillar_ionic-side"))
                .texture("charcoal_pillar_ionic_spiral", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_ionic_spiral", "vertical_both", Chisel.prefix("block/charcoal/charcoal_pillar_basic_spiral-vertical_both"))
                .texture("charcoal_pillar_ionic_spiral", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_ionic-side"))
                .addVariant("charcoal_pillar_large_basic_triple", ChiselModelHandlers.CTMV).translation("charcoal_pillar_large_basic_triple", "Charcoal", "Large Basic Triple Pillar")
                .texture("charcoal_pillar_large_basic_triple", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_large_basic_triple", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_large_basic_triple", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_large_basic_triple-side"))
                .addVariant("charcoal_pillar_large_ionic_triple", ChiselModelHandlers.CTMV).translation("charcoal_pillar_large_ionic_triple", "Charcoal", "Large Ionic Triple Pillar")
                .texture("charcoal_pillar_large_ionic_triple", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_large_ionic_triple", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_large_ionic_triple", "vertical_both", Chisel.prefix("block/charcoal/charcoal_pillar_large_basic_triple-vertical_both"))
                .texture("charcoal_pillar_large_ionic_triple", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_large_ionic_triple-side"))
                .addVariant("charcoal_pillar_meander", ChiselModelHandlers.CTMV).translation("charcoal_pillar_meander", "Charcoal", "Meander Pillar")
                .texture("charcoal_pillar_meander", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_meander", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_meander", "vertical_both", Chisel.prefix("block/charcoal/charcoal_pillar_ionic-vertical_both"))
                .texture("charcoal_pillar_meander", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_meander-side"))
                .addVariant("charcoal_pillar_meander_dent", ChiselModelHandlers.CTMV).translation("charcoal_pillar_meander_dent", "Charcoal", "Meander Dent Pillar")
                .texture("charcoal_pillar_meander_dent", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_meander_dent", "side", Chisel.prefix("block/charcoal/charcoal_pillar_meander-side"))
                .texture("charcoal_pillar_meander_dent", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_meander_dent", "vertical_both", Chisel.prefix("block/charcoal/charcoal_pillar_basic_dent-vertical_both"))
                .texture("charcoal_pillar_meander_dent", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_meander-side"))
                .addVariant("charcoal_pillar_meander_plain", ChiselModelHandlers.CTMV).translation("charcoal_pillar_meander_plain", "Charcoal", "Meander Plain Pillar")
                .texture("charcoal_pillar_meander_plain", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_meander_plain", "side", Chisel.prefix("block/charcoal/charcoal_pillar_meander-side"))
                .texture("charcoal_pillar_meander_plain", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_meander_plain", "vertical_both", Chisel.prefix("block/charcoal/charcoal_pillar_basic_plain-vertical_both"))
                .texture("charcoal_pillar_meander_plain", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_meander-side"))
                .addVariant("charcoal_pillar_meander_round", ChiselModelHandlers.CTMV).translation("charcoal_pillar_meander_round", "Charcoal", "Meander Round Pillar")
                .texture("charcoal_pillar_meander_round", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_meander_round", "side", Chisel.prefix("block/charcoal/charcoal_pillar_meander-side"))
                .texture("charcoal_pillar_meander_round", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_meander_round", "vertical_both", Chisel.prefix("block/charcoal/charcoal_pillar_basic_round-vertical_both"))
                .texture("charcoal_pillar_meander_round", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_meander-side"))
                .addVariant("charcoal_pillar_meander_spiral", ChiselModelHandlers.CTMV).translation("charcoal_pillar_meander_spiral", "Charcoal", "Meander Spiral Pillar")
                .texture("charcoal_pillar_meander_spiral", "bottom", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_meander_spiral", "side", Chisel.prefix("block/charcoal/charcoal_pillar_meander-side"))
                .texture("charcoal_pillar_meander_spiral", "top", Chisel.prefix("block/charcoal/charcoal_pillar_basic-bottom"))
                .texture("charcoal_pillar_meander_spiral", "vertical_both", Chisel.prefix("block/charcoal/charcoal_pillar_basic_spiral-vertical_both"))
                .texture("charcoal_pillar_meander_spiral", "vertical_none", Chisel.prefix("block/charcoal/charcoal_pillar_meander-side"))
                .addVariant("charcoal_plate").translation("charcoal_plate", "Charcoal", "Plate")
                .texture("charcoal_plate", Chisel.prefix("block/charcoal/charcoal_plate_connected"))
                .addVariant("charcoal_plate_connected", ChiselModelHandlers.CONNECTED).translation("charcoal_plate_connected", "Charcoal", "Plate Connected")
                .texture("charcoal_plate_connected", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_border_square-ctm_cornerless"))
                .addVariant("charcoal_polished").translation("charcoal_polished", "Charcoal", "Polished")
                .addVariant("charcoal_polished_encased", ChiselModelHandlers.CONNECTED).translation("charcoal_polished_encased", "Charcoal", "Polished Encased")
                .addVariant("charcoal_prism").translation("charcoal_prism", "Charcoal", "Prismatic Charcoal")
                .addVariant("charcoal_raw").translation("charcoal_raw", "Charcoal", "Raw")
                .addVariant("charcoal_road").translation("charcoal_road", "Charcoal", "Road")
                .addVariant("charcoal_slanted", ChiselModelHandlers.MULTIBLOCK_2X2).translation("charcoal_slanted", "Charcoal", "Slanted")
                .texture("charcoal_slanted", "2x2_top_left", Chisel.prefix("block/charcoal/charcoal_slanted"))
                .addVariant("charcoal_tiles_medium").translation("charcoal_tiles_medium", "Charcoal", "Medium Tiles")
                .addVariant("charcoal_tiles_large", ChiselModelHandlers.CONNECTED).translation("charcoal_tiles_large", "Charcoal", "Large Tiles")
                .addVariant("charcoal_tiles_small").translation("charcoal_tiles_small", "Charcoal", "Small Tiles")
                .addVariant("charcoal_twisted", ChiselModelHandlers.TBS).translation("charcoal_twisted", "Charcoal", "Twisted")
                .texture("charcoal_twisted", "bottom", Chisel.prefix("block/charcoal/charcoal_twisted-top"))
                .addVariant("charcoal_weaver", ChiselModelHandlers.CONNECTED).translation("charcoal_weaver", "Charcoal", "Weaver")
                .addVariant("charcoal_zag", ChiselModelHandlers.V4).translation("charcoal_zag", "Charcoal", "Zag")
                .texture("charcoal_zag", "v4_top_right", Chisel.prefix("block/charcoal/charcoal_zag-v4_bottom_left"))
                .addVariant("charcoal_crate", ChiselModelHandlers.CONNECTED).translation("charcoal_crate", "Charcoal", "Crate")
                .addVariant("charcoal_herringbone").translation("charcoal_herringbone", "Charcoal", "Herringbone")
                .addVariant("charcoal_herringbone_encased", ChiselModelHandlers.CONNECTED).translation("charcoal_herringbone_encased", "Charcoal", "Encased Herringbone")
                .texture("charcoal_herringbone_encased", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_herringbone"))
                .addVariant("charcoal_medallion").translation("charcoal_medallion", "Charcoal", "Medallion")
                .addVariant("charcoal_medallion_encased", ChiselModelHandlers.CONNECTED).translation("charcoal_medallion_encased", "Charcoal", "Encased Medallion")
                .texture("charcoal_medallion_encased", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_medallion"))
                .addVariant("charcoal_dots").translation("charcoal_dots", "Charcoal", "Dots")
                .addVariant("charcoal_dots_encased", ChiselModelHandlers.CONNECTED).translation("charcoal_dots_encased", "Charcoal", "Encased Dots")
                .texture("charcoal_dots_encased", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_dots"))
                .addVariant("charcoal_heart").translation("charcoal_heart", "Charcoal", "Heart")
                .addVariant("charcoal_star").translation("charcoal_star", "Charcoal", "Star")
                .addVariant("charcoal_plating").translation("charcoal_plating", "Charcoal", "Plating")
                .addVariant("charcoal_lodestone").translation("charcoal_lodestone", "Charcoal", "Lodestone")
                .texture("charcoal_lodestone", Chisel.prefix("block/charcoal/charcoal_lodestone_connected"))
                .addVariant("charcoal_lodestone_connected", ChiselModelHandlers.CONNECTED).translation("charcoal_lodestone_connected", "Charcoal", "Lodestone Connected")
                .texture("charcoal_lodestone_connected", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_lodestone_connected"))
                .addVariant("charcoal_plank").translation("charcoal_plank", "Charcoal", "Plank")
                .texture("charcoal_plank", Chisel.prefix("block/charcoal/charcoal_plank_connected"))
                .addVariant("charcoal_plank_connected", ChiselModelHandlers.CONNECTED).translation("charcoal_plank_connected", "Charcoal", "Plank Connected")
                .addVariant("charcoal_frame").translation("charcoal_frame", "Charcoal", "Frame")
                .addVariant("charcoal_panel_1").translation("charcoal_panel_1", "Charcoal", "Panel 1")
                .addVariant("charcoal_panel_2").translation("charcoal_panel_2", "Charcoal", "Panel 2")
                .addVariant("charcoal_panel_3").translation("charcoal_panel_3", "Charcoal", "Panel 3")
                .addVariant("charcoal_skull_creeper").translation("charcoal_skull_creeper", "Charcoal", "Creeper Skull")
                .addVariant("charcoal_skull_skeleton").translation("charcoal_skull_skeleton", "Charcoal", "Skeleton Skull")
                .addVariant("charcoal_stripes").translation("charcoal_stripes", "Charcoal", "Stripes")
                .addVariant("charcoal_stripes_encased", ChiselModelHandlers.CONNECTED).translation("charcoal_stripes_encased", "Charcoal", "Encased Stripes")
                .texture("charcoal_stripes_encased", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_stripes"))
                .addVariant("charcoal_chisel_1").translation("charcoal_chisel_1", "Charcoal", "Chisel 1")
                .addVariant("charcoal_chisel_2").translation("charcoal_chisel_2", "Charcoal", "Chisel 2")
                .addVariant("charcoal_chisel_3").translation("charcoal_chisel_3", "Charcoal", "Chisel 3")
                .addVariant("charcoal_chisel_4").translation("charcoal_chisel_4", "Charcoal", "Chisel 4")
                .addVariant("charcoal_chisel_5").translation("charcoal_chisel_5", "Charcoal", "Chisel 5")
                .addVariant("charcoal_chisel_6").translation("charcoal_chisel_6", "Charcoal", "Chisel 6")
                .addVariant("charcoal_facet").translation("charcoal_facet", "Charcoal", "Facet")
                .addVariant("charcoal_facet_small").translation("charcoal_facet_small", "Charcoal", "Small Facet")
                .addVariant("charcoal_facet_small_encased", ChiselModelHandlers.CONNECTED).translation("charcoal_facet_small_encased", "Charcoal", "Encased Small Facet")
                .texture("charcoal_facet_small_encased", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_facet_small"))
                .addVariant("charcoal_shiny").translation("charcoal_shiny", "Charcoal", "Shiny")
                .texture("charcoal_shiny", Chisel.prefix("block/charcoal/charcoal_shiny_connected"))
                .addVariant("charcoal_shiny_connected", ChiselModelHandlers.CONNECTED).translation("charcoal_shiny_connected", "Charcoal", "Shiny Connected")
                .addVariant("charcoal_gem").translation("charcoal_gem", "Charcoal", "Gem")
                .addVariant("charcoal_gem_1").translation("charcoal_gem_1", "Charcoal", "Gem 1")
                .texture("charcoal_gem_1", Chisel.prefix("block/charcoal/charcoal_gem_1_connected"))
                .addVariant("charcoal_gem_1_connected", ChiselModelHandlers.CONNECTED).translation("charcoal_gem_1_connected", "Charcoal", "Gem 1 Connected")
                .texture("charcoal_gem_1_connected", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_border_square-ctm_cornerless"))
                .addVariant("charcoal_gem_2").translation("charcoal_gem_2", "Charcoal", "Gem 2")
                .texture("charcoal_gem_2", Chisel.prefix("block/charcoal/charcoal_gem_2_connected"))
                .addVariant("charcoal_gem_2_connected", ChiselModelHandlers.CONNECTED).translation("charcoal_gem_2_connected", "Charcoal", "Gem 2 Connected")
                .texture("charcoal_gem_2_connected", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_border_square-ctm_cornerless"))
                .addVariant("charcoal_gem_3").translation("charcoal_gem_3", "Charcoal", "Gem 3")
                .texture("charcoal_gem_3", Chisel.prefix("block/charcoal/charcoal_gem_3_connected"))
                .addVariant("charcoal_gem_3_connected", ChiselModelHandlers.CONNECTED).translation("charcoal_gem_3_connected", "Charcoal", "Gem 3 Connected")
                .addVariant("charcoal_bricks_square").translation("charcoal_bricks_square", "Charcoal", "Square Bricks")
                .addVariant("charcoal_slab").translation("charcoal_slab", "Charcoal", "Slab")
                .addVariant("charcoal_scaffold").translation("charcoal_scaffold", "Charcoal", "Scaffold")
                .addVariant("charcoal_scaffold_encased", ChiselModelHandlers.CONNECTED).translation("charcoal_scaffold_encased", "Charcoal", "Encased Scaffold")
                .texture("charcoal_scaffold_encased", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_scaffold"))
                .addVariant("charcoal_tiles_inlayed").translation("charcoal_tiles_inlayed", "Charcoal", "Inlayed Tiles")
                .addVariant("charcoal_waves", ChiselModelHandlers.MULTIBLOCK_2X2).translation("charcoal_waves", "Charcoal", "Waves")
                .texture("charcoal_waves", "2x2_top_left", Chisel.prefix("block/charcoal/charcoal_waves"))
                .addVariant("charcoal_parquet").translation("charcoal_parquet", "Charcoal", "Parquet")
                .addVariant("charcoal_parquet_encased", ChiselModelHandlers.CONNECTED).translation("charcoal_parquet_encased", "Charcoal", "Encased Parquet")
                .texture("charcoal_parquet_encased", "ctm_cornerless", Chisel.prefix("block/charcoal/charcoal_parquet"))
                .addVariant("charcoal_border_square_small", ChiselModelHandlers.CONNECTED).translation("charcoal_border_square_small", "Charcoal", "Small Square Border")
                .addVariant("charcoal_cobble").translation("charcoal_cobble", "Charcoal", "Cobble")
                .addVariant("charcoal_bricks_large_rough", ChiselModelHandlers.MULTIBLOCK_2X2).translation("charcoal_bricks_large_rough", "Charcoal", "Large Rough Bricks")
                .addVariant("charcoal_tiles_small_encased", ChiselModelHandlers.CONNECTED).translation("charcoal_tiles_small_encased", "Charcoal", "Encased Small Tiles")
                .addVariant("charcoal_bricks_round").translation("charcoal_bricks_round", "Charcoal", "Round Bricks")
                .build());

        COAL_COKE = ChiselFamily.build("coal_coke", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE))
                .addVariant("coal_coke_array", ChiselModelHandlers.MULTIBLOCK_2X2).translation("coal_coke_array", "Coal Coke", "Array")
                .texture("coal_coke_array", "2x2_top_left", Chisel.prefix("block/coal_coke/coal_coke_array"))
                .addVariant("coal_coke_braid").translation("coal_coke_braid", "Coal Coke", "Braid")
                .addVariant("coal_coke_chaotic_bricks", ChiselModelHandlers.MULTIBLOCK_3X3).translation("coal_coke_chaotic_bricks", "Coal Coke", "Chaotic Bricks")
                .texture("coal_coke_chaotic_bricks", "3x3_top_left", Chisel.prefix("block/coal_coke/coal_coke_chaotic_bricks"))
                .addVariant("coal_coke_chaotic_medium").translation("coal_coke_chaotic_medium", "Coal Coke", "Coal Coke Bricks")
                .addVariant("coal_coke_chaotic_small").translation("coal_coke_chaotic_small", "Coal Coke", "Coal Coke Small Tiles")
                .addVariant("coal_coke_circular", ChiselModelHandlers.CONNECTED).translation("coal_coke_circular", "Coal Coke", "Circular")
                .texture("coal_coke_circular", "ctm_cornerless", Chisel.prefix("block/coal_coke/coal_coke_dent-ctm_cornerless"))
                .addVariant("coal_coke_cracked").translation("coal_coke_cracked", "Coal Coke", "Cracked")
                .addVariant("coal_coke_cracked_bricks").translation("coal_coke_cracked_bricks", "Coal Coke", "Cracked Bricks")
                .addVariant("coal_coke_cuts", ChiselModelHandlers.MULTIBLOCK_4X4).translation("coal_coke_cuts", "Coal Coke", "Cuts")
                .texture("coal_coke_cuts", "4x4_row_0_column_0", Chisel.prefix("block/coal_coke/coal_coke_cuts"))
                .addVariant("coal_coke_dent", ChiselModelHandlers.CONNECTED).translation("coal_coke_dent", "Coal Coke", "Dent")
                .addVariant("coal_coke_encased_bricks", ChiselModelHandlers.CONNECTED).translation("coal_coke_encased_bricks", "Coal Coke", "Encased Bricks")
                .addVariant("coal_coke_french_1").translation("coal_coke_french_1", "Coal Coke", "French 1")
                .addVariant("coal_coke_french_2").translation("coal_coke_french_2", "Coal Coke", "French 2")
                .addVariant("coal_coke_jellybean", ChiselModelHandlers.MULTIBLOCK_2X2).translation("coal_coke_jellybean", "Coal Coke", "Jellybean")
                .texture("coal_coke_jellybean", "2x2_top_left", Chisel.prefix("block/coal_coke/coal_coke_jellybean"))
                .addVariant("coal_coke_layers").translation("coal_coke_layers", "Coal Coke", "Layers")
                .addVariant("coal_coke_mosaic", ChiselModelHandlers.CONNECTED).translation("coal_coke_mosaic", "Coal Coke", "Mosaic")
                .texture("coal_coke_mosaic", "ctm_cornerless", Chisel.prefix("block/coal_coke/coal_coke_raw"))
                .addVariant("coal_coke_ornate").translation("coal_coke_ornate", "Coal Coke", "Ornate Coal Coke")
                .addVariant("coal_coke_panel").translation("coal_coke_panel", "Coal Coke", "Panel")
                .addVariant("coal_coke_pillar", ChiselModelHandlers.TBS).translation("coal_coke_pillar", "Coal Coke", "Pillar")
                .texture("coal_coke_pillar", "bottom", Chisel.prefix("block/coal_coke/coal_coke_pillar-top"))
                .addVariant("coal_coke_prism").translation("coal_coke_prism", "Coal Coke", "Prismatic Coal Coke")
                .addVariant("coal_coke_raw").translation("coal_coke_raw", "Coal Coke", "Raw")
                .addVariant("coal_coke_road").translation("coal_coke_road", "Coal Coke", "Road")
                .addVariant("coal_coke_slanted", ChiselModelHandlers.MULTIBLOCK_2X2).translation("coal_coke_slanted", "Coal Coke", "Slanted")
                .texture("coal_coke_slanted", "2x2_bottom_left", Chisel.prefix("block/coal_coke/coal_coke_slanted"))
                .texture("coal_coke_slanted", "2x2_bottom_right", Chisel.prefix("block/coal_coke/coal_coke_slanted-2x2_top_right"))
                .texture("coal_coke_slanted", "2x2_top_left", Chisel.prefix("block/coal_coke/coal_coke_slanted"))
                .addVariant("coal_coke_small_bricks").translation("coal_coke_small_bricks", "Coal Coke", "Small Bricks")
                .addVariant("coal_coke_soft_bricks").translation("coal_coke_soft_bricks", "Coal Coke", "Soft Bricks")
                .addVariant("coal_coke_solid_bricks").translation("coal_coke_solid_bricks", "Coal Coke", "Solid Bricks")
                .addVariant("coal_coke_tiles_large", ChiselModelHandlers.CONNECTED).translation("coal_coke_tiles_large", "Coal Coke", "Large Tiles")
                .addVariant("coal_coke_tiles_medium").translation("coal_coke_tiles_medium", "Coal Coke", "Medium Tiles")
                .addVariant("coal_coke_tiles_small").translation("coal_coke_tiles_small", "Coal Coke", "Small Tiles")
                .addVariant("coal_coke_triple_bricks").translation("coal_coke_triple_bricks", "Coal Coke", "Triple Bricks")
                .addVariant("coal_coke_twisted", ChiselModelHandlers.TBS).translation("coal_coke_twisted", "Coal Coke", "Twisted")
                .texture("coal_coke_twisted", "bottom", Chisel.prefix("block/coal_coke/coal_coke_twisted-top"))
                .addVariant("coal_coke_weaver", ChiselModelHandlers.CONNECTED).translation("coal_coke_weaver", "Coal Coke", "Weaver")
                .addVariant("coal_coke_zag", ChiselModelHandlers.AR).translation("coal_coke_zag", "Coal Coke", "Zag")
                .texture("coal_coke_zag", "ar_variant_1", Chisel.prefix("block/coal_coke/coal_coke_zag"))
                .build());

        ALUMINUM = ChiselFamily.build("aluminum", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("aluminum_bad_greggy", ChiselModelHandlers.CONNECTED).translation("aluminum_bad_greggy", "Aluminum", "An Old Relic from the land of Oneteufyv")
                .addVariant("aluminum_bolted").translation("aluminum_bolted", "Aluminum", "Fancy Bolted Plating")
                .addVariant("aluminum_caution", ChiselModelHandlers.CONNECTED).translation("aluminum_caution", "Aluminum", "Caution Stripes")
                .addVariant("aluminum_crate", ChiselModelHandlers.CONNECTED).translation("aluminum_crate", "Aluminum", "Shipping Crate")
                .addVariant("aluminum_machine").translation("aluminum_machine", "Aluminum", "Machine")
                .addVariant("aluminum_scaffold", ChiselModelHandlers.CONNECTED).translation("aluminum_scaffold", "Aluminum", "Scaffold")
                .addVariant("aluminum_thermal", ChiselModelHandlers.TBS).translation("aluminum_thermal", "Aluminum", "Thermal")
                .build());

        BRONZE = ChiselFamily.build("bronze", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("bronze_bad_greggy", ChiselModelHandlers.CONNECTED).translation("bronze_bad_greggy", "Bronze", "An Old Relic from the land of Oneteufyv")
                .addVariant("bronze_bolted").translation("bronze_bolted", "Bronze", "Fancy Bolted Plating")
                .addVariant("bronze_caution", ChiselModelHandlers.CONNECTED).translation("bronze_caution", "Bronze", "Caution Stripes")
                .addVariant("bronze_crate", ChiselModelHandlers.CONNECTED).translation("bronze_crate", "Bronze", "Shipping Crate")
                .addVariant("bronze_machine").translation("bronze_machine", "Bronze", "Machine")
                .addVariant("bronze_scaffold", ChiselModelHandlers.CONNECTED).translation("bronze_scaffold", "Bronze", "Scaffold")
                .addVariant("bronze_thermal", ChiselModelHandlers.TBS).translation("bronze_thermal", "Bronze", "Thermal")
                .build());

        COBALT = ChiselFamily.build("cobalt", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("cobalt_bad_greggy", ChiselModelHandlers.CONNECTED).translation("cobalt_bad_greggy", "Cobalt", "An Old Relic from the land of Oneteufyv")
                .addVariant("cobalt_bolted").translation("cobalt_bolted", "Cobalt", "Fancy Bolted Plating")
                .addVariant("cobalt_caution", ChiselModelHandlers.CONNECTED).translation("cobalt_caution", "Cobalt", "Caution Stripes")
                .addVariant("cobalt_crate", ChiselModelHandlers.CONNECTED).translation("cobalt_crate", "Cobalt", "Shipping Crate")
                .addVariant("cobalt_machine").translation("cobalt_machine", "Cobalt", "Machine")
                .addVariant("cobalt_scaffold", ChiselModelHandlers.CONNECTED).translation("cobalt_scaffold", "Cobalt", "Scaffold")
                .addVariant("cobalt_thermal", ChiselModelHandlers.TBS).translation("cobalt_thermal", "Cobalt", "Thermal")
                .build());

        ELECTRUM = ChiselFamily.build("electrum", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("electrum_bad_greggy", ChiselModelHandlers.CONNECTED).translation("electrum_bad_greggy", "Electrum", "An Old Relic from the land of Oneteufyv")
                .addVariant("electrum_bolted").translation("electrum_bolted", "Electrum", "Fancy Bolted Plating")
                .addVariant("electrum_caution", ChiselModelHandlers.CONNECTED).translation("electrum_caution", "Electrum", "Caution Stripes")
                .addVariant("electrum_crate", ChiselModelHandlers.CONNECTED).translation("electrum_crate", "Electrum", "Shipping Crate")
                .addVariant("electrum_machine").translation("electrum_machine", "Electrum", "Machine")
                .addVariant("electrum_scaffold", ChiselModelHandlers.CONNECTED).translation("electrum_scaffold", "Electrum", "Scaffold")
                .addVariant("electrum_thermal", ChiselModelHandlers.TBS).translation("electrum_thermal", "Electrum", "Thermal")
                .build());

        INVAR = ChiselFamily.build("invar", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("invar_bad_greggy", ChiselModelHandlers.CONNECTED).translation("invar_bad_greggy", "Invar", "An Old Relic from the land of Oneteufyv")
                .addVariant("invar_bolted").translation("invar_bolted", "Invar", "Fancy Bolted Plating")
                .addVariant("invar_caution", ChiselModelHandlers.CONNECTED).translation("invar_caution", "Invar", "Caution Stripes")
                .addVariant("invar_crate", ChiselModelHandlers.CONNECTED).translation("invar_crate", "Invar", "Shipping Crate")
                .addVariant("invar_machine").translation("invar_machine", "Invar", "Machine")
                .addVariant("invar_scaffold", ChiselModelHandlers.CONNECTED).translation("invar_scaffold", "Invar", "Scaffold")
                .addVariant("invar_thermal", ChiselModelHandlers.TBS).translation("invar_thermal", "Invar", "Thermal")
                .build());

        LEAD = ChiselFamily.build("lead", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("lead_bad_greggy", ChiselModelHandlers.CONNECTED).translation("lead_bad_greggy", "Lead", "An Old Relic from the land of Oneteufyv")
                .addVariant("lead_bolted").translation("lead_bolted", "Lead", "Fancy Bolted Plating")
                .addVariant("lead_caution", ChiselModelHandlers.CONNECTED).translation("lead_caution", "Lead", "Caution Stripes")
                .addVariant("lead_crate", ChiselModelHandlers.CONNECTED).translation("lead_crate", "Lead", "Shipping Crate")
                .addVariant("lead_machine").translation("lead_machine", "Lead", "Machine")
                .addVariant("lead_scaffold", ChiselModelHandlers.CONNECTED).translation("lead_scaffold", "Lead", "Scaffold")
                .addVariant("lead_thermal", ChiselModelHandlers.TBS).translation("lead_thermal", "Lead", "Thermal")
                .build());

        NICKEL = ChiselFamily.build("nickel", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("nickel_bad_greggy", ChiselModelHandlers.CONNECTED).translation("nickel_bad_greggy", "Nickel", "An Old Relic from the land of Oneteufyv")
                .addVariant("nickel_bolted").translation("nickel_bolted", "Nickel", "Fancy Bolted Plating")
                .addVariant("nickel_caution", ChiselModelHandlers.CONNECTED).translation("nickel_caution", "Nickel", "Caution Stripes")
                .addVariant("nickel_crate").translation("nickel_crate", "Nickel", "Shipping Crate")
                .addVariant("nickel_machine").translation("nickel_machine", "Nickel", "Machine")
                .addVariant("nickel_scaffold", ChiselModelHandlers.CONNECTED).translation("nickel_scaffold", "Nickel", "Scaffold")
                .addVariant("nickel_thermal", ChiselModelHandlers.TBS).translation("nickel_thermal", "Nickel", "Thermal")
                .build());

        PLATINUM = ChiselFamily.build("platinum", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("platinum_bad_greggy", ChiselModelHandlers.CONNECTED).translation("platinum_bad_greggy", "Platinum", "An Old Relic from the land of Oneteufyv")
                .addVariant("platinum_bolted").translation("platinum_bolted", "Platinum", "Fancy Bolted Plating")
                .addVariant("platinum_caution", ChiselModelHandlers.CONNECTED).translation("platinum_caution", "Platinum", "Caution Stripes")
                .addVariant("platinum_crate", ChiselModelHandlers.CONNECTED).translation("platinum_crate", "Platinum", "Shipping Crate")
                .addVariant("platinum_machine").translation("platinum_machine", "Platinum", "Machine")
                .addVariant("platinum_scaffold", ChiselModelHandlers.CONNECTED).translation("platinum_scaffold", "Platinum", "Scaffold")
                .addVariant("platinum_thermal", ChiselModelHandlers.TBS).translation("platinum_thermal", "Platinum", "Thermal")
                .build());

        SILVER = ChiselFamily.build("silver", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("silver_125").translation("silver_125", "Silver", "125")
                .addVariant("silver_bad_greggy", ChiselModelHandlers.CONNECTED).translation("silver_bad_greggy", "Silver", "An Old Relic from the land of Oneteufyv")
                .addVariant("silver_bolted").translation("silver_bolted", "Silver", "Fancy Bolted Plating")
                .addVariant("silver_caution", ChiselModelHandlers.CONNECTED).translation("silver_caution", "Silver", "Caution Stripes")
                .addVariant("silver_crate", ChiselModelHandlers.CONNECTED).translation("silver_crate", "Silver", "Shipping Crate")
                .addVariant("silver_scaffold", ChiselModelHandlers.CONNECTED).translation("silver_scaffold", "Silver", "Scaffold")
                .addVariant("silver_thermal", ChiselModelHandlers.TBS).translation("silver_thermal", "Silver", "Thermal")
                .build());

        STEEL = ChiselFamily.build("steel", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("steel_125").translation("steel_125", "Steel", "125")
                .addVariant("steel_bad_greggy", ChiselModelHandlers.CONNECTED).translation("steel_bad_greggy", "Steel", "An Old Relic from the land of Oneteufyv")
                .addVariant("steel_bolted").translation("steel_bolted", "Steel", "Fancy Bolted Plating")
                .addVariant("steel_caution", ChiselModelHandlers.CONNECTED).translation("steel_caution", "Steel", "Caution Stripes")
                .addVariant("steel_crate", ChiselModelHandlers.CONNECTED).translation("steel_crate", "Steel", "Shipping Crate")
                .addVariant("steel_egregious", ChiselModelHandlers.CONNECTED).translation("steel_egregious", "Steel", "Egregiously Bordered Block")
                .addVariant("steel_scaffold", ChiselModelHandlers.CONNECTED).translation("steel_scaffold", "Steel", "Scaffold")
                .addVariant("steel_thermal", ChiselModelHandlers.TBS).translation("steel_thermal", "Steel", "Thermal")
                .build());

        THAUMIUM = ChiselFamily.build("thaumium", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("thaumium_bevel").translation("thaumium_bevel", "Thaumium", "Bevel")
                .addVariant("thaumium_block").translation("thaumium_block", "Thaumium", "Block")
                .addVariant("thaumium_bricks", ChiselModelHandlers.CONNECTED).translation("thaumium_bricks", "Thaumium", "Bricks")
                .texture("thaumium_bricks", "ctm_cornerless", Chisel.prefix("block/thaumium/thaumium_bricks-ctm_corner"))
                .texture("thaumium_bricks", "ctm_horizontal", Chisel.prefix("block/thaumium/thaumium_bricks"))
                .texture("thaumium_bricks", "ctm_vertical", Chisel.prefix("block/thaumium/thaumium_bricks-ctm_corner"))
                .addVariant("thaumium_chunks").translation("thaumium_chunks", "Thaumium", "Chunks")
                .addVariant("thaumium_lattice").translation("thaumium_lattice", "Thaumium", "Lattice")
                .addVariant("thaumium_ornate").translation("thaumium_ornate", "Thaumium", "Ornate")
                .addVariant("thaumium_planks", ChiselModelHandlers.CONNECTED).translation("thaumium_planks", "Thaumium", "Planks")
                .addVariant("thaumium_runes_purple", ChiselModelHandlers.V9).translation("thaumium_runes_purple", "Thaumium", "Purple Runes")
                .texture("thaumium_runes_purple", "v9_top_left", Chisel.prefix("block/thaumium/thaumium_runes_purple"))
                .addVariant("thaumium_runes", ChiselModelHandlers.V9).translation("thaumium_runes", "Thaumium", "Runes")
                .texture("thaumium_runes", "v9_top_left", Chisel.prefix("block/thaumium/thaumium_runes"))
                .addVariant("thaumium_small").translation("thaumium_small", "Thaumium", "Small")
                .addVariant("thaumium_totem", ChiselModelHandlers.R4).translation("thaumium_totem", "Thaumium", "Totem")
                .texture("thaumium_totem", "r4_top_right", Chisel.prefix("block/thaumium/thaumium_totem"))
                .build());

        TIN = ChiselFamily.build("tin", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("tin_125").translation("tin_125", "Tin", "125")
                .addVariant("tin_bad_greggy", ChiselModelHandlers.CONNECTED).translation("tin_bad_greggy", "Tin", "An Old Relic from the land of Oneteufyv")
                .addVariant("tin_bolted").translation("tin_bolted", "Tin", "Fancy Bolted Plating")
                .addVariant("tin_caution", ChiselModelHandlers.CONNECTED).translation("tin_caution", "Tin", "Caution Stripes")
                .addVariant("tin_crate", ChiselModelHandlers.CONNECTED).translation("tin_crate", "Tin", "Shipping Crate")
                .addVariant("tin_egregious", ChiselModelHandlers.CONNECTED).translation("tin_egregious", "Tin", "Egregiously Bordered Block")
                .addVariant("tin_scaffold", ChiselModelHandlers.CONNECTED).translation("tin_scaffold", "Tin", "Scaffold")
                .addVariant("tin_thermal", ChiselModelHandlers.TBS).translation("tin_thermal", "Tin", "Thermal")
                .build());

        URANIUM = ChiselFamily.build("uranium", builder -> builder
                .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BLOCK))
                .addVariant("uranium_125").translation("uranium_125", "Uranium", "125")
                .addVariant("uranium_bad_greggy", ChiselModelHandlers.CONNECTED).translation("uranium_bad_greggy", "Uranium", "An Old Relic from the land of Oneteufyv")
                .addVariant("uranium_bolted").translation("uranium_bolted", "Uranium", "Fancy Bolted Plating")
                .addVariant("uranium_caution", ChiselModelHandlers.CONNECTED).translation("uranium_caution", "Uranium", "Caution Stripes")
                .addVariant("uranium_crate", ChiselModelHandlers.CONNECTED).translation("uranium_crate", "Uranium", "Shipping Crate")
                .addVariant("uranium_machine").translation("uranium_machine", "Uranium", "Machine")
                .addVariant("uranium_scaffold", ChiselModelHandlers.CONNECTED).translation("uranium_scaffold", "Uranium", "Scaffold")
                .addVariant("uranium_thermal", ChiselModelHandlers.TBS).translation("uranium_thermal", "Uranium", "Thermal")
                .build());

        FAMILIES = List.of(ALUMINUM, BRONZE, COBALT, ELECTRUM, INVAR, LEAD, NICKEL, PLATINUM, SILVER, STEEL, THAUMIUM, TIN, URANIUM, CHARCOAL, COAL_COKE);
    }

    private ModdedMetalFamilies() {
    }

    public static List<ChiselFamily> families() {
        return FAMILIES;
    }
}
